name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.1.java11'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-dep: '1.10.1.469'
    - name: Install dependencies
      run: lein deps
      working-directory: ./hello
    - name: Run tests
      run: lein test
      working-directory: ./hello
